[theme]

# Primary accent for interactive elements
primaryColor = '#3ACB89'

# Background color for the main content area
backgroundColor = '#292929'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#3ACB89'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
